### ISSUE TITLE
请问哪里能下载saespot的gae版本最新版？

### ISSUE THREAD

**Issue by lifeidle** [ego008/youbbs#10]
ego大大，我找了半天都没找到，想再学习下，万分感谢！！！

**Comment by lifeidle** [comment]
ego大大，我找到了Google Code上的存档文件：
https://code.google.com/archive/p/saespot/
不过页面上的gae版本下载一直出错。
老大能不能把gae版本也开源到github，我也好来Star啊！

**Comment by ego008** [comment]
https://github.com/ego008/gae-bbs
